#!/bin/bash

# CI/CD Flask Project - Setup and Test Script
# Run this script after pushing to GitHub

echo "================================"
echo "🚀 CI/CD Flask Project Setup"
echo "================================"
echo ""

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Step 1: Local Testing
echo -e "${BLUE}Step 1: Local Testing${NC}"
echo "Run these commands to test locally:"
echo ""
echo "  python -m venv venv"
echo "  source venv/bin/activate  # On Windows: venv\\Scripts\\activate"
echo "  pip install -r requirements.txt"
echo "  python app.py"
echo ""
echo "  # In another terminal:"
echo "  curl http://localhost:5000/"
echo "  curl http://localhost:5000/health"
echo ""
read -p "Press Enter when you've tested locally..."

# Step 2: Run Tests
echo ""
echo -e "${BLUE}Step 2: Run Tests${NC}"
echo "Run pytest to ensure all tests pass:"
echo ""
echo "  pytest -v"
echo "  pytest --cov=app --cov-report=html"
echo ""
read -p "Press Enter when tests pass..."

# Step 3: Test Docker Build
echo ""
echo -e "${BLUE}Step 3: Test Docker Build${NC}"
echo "Build and test the Docker image:"
echo ""
echo "  docker build -t flask-cicd-app ."
echo "  docker run -d -p 5000:5000 --name test-app flask-cicd-app"
echo "  sleep 5"
echo "  curl http://localhost:5000/health"
echo "  docker stop test-app && docker rm test-app"
echo ""
read -p "Press Enter when Docker works..."

# Step 4: Git Setup
echo ""
echo -e "${BLUE}Step 4: Initialize Git Repository${NC}"
echo ""
echo "Run these commands:"
echo ""
echo "  git init"
echo "  git add ."
echo "  git commit -m 'Initial commit: CI/CD Flask project'"
echo "  git branch -M main"
echo ""
read -p "Press Enter when committed..."

# Step 5: Create GitHub Repository
echo ""
echo -e "${BLUE}Step 5: Create GitHub Repository${NC}"
echo ""
echo "1. Go to https://github.com/new"
echo "2. Repository name: cicd-flask-project"
echo "3. Description: Flask app with CI/CD pipeline"
echo "4. Make it Public"
echo "5. DON'T initialize with README (we have one)"
echo "6. Click 'Create repository'"
echo ""
read -p "Press Enter when repository is created..."

# Step 6: Push to GitHub
echo ""
echo -e "${BLUE}Step 6: Push to GitHub${NC}"
echo ""
echo "Replace YOUR_USERNAME with your GitHub username:"
echo ""
echo "  git remote add origin https://github.com/YOUR_USERNAME/cicd-flask-project.git"
echo "  git push -u origin main"
echo ""
read -p "Press Enter when pushed..."

# Step 7: Watch GitHub Actions
echo ""
echo -e "${BLUE}Step 7: Watch GitHub Actions Pipeline${NC}"
echo ""
echo "1. Go to your repository on GitHub"
echo "2. Click the 'Actions' tab"
echo "3. Watch your pipeline run! 🎉"
echo ""
echo "You should see:"
echo "  ✅ Test job running"
echo "  ✅ Lint job running"
echo "  ✅ Build job running"
echo "  ✅ All jobs passing!"
echo ""
read -p "Press Enter when pipeline succeeds..."

# Step 8: Optional - Docker Hub Setup
echo ""
echo -e "${YELLOW}Step 8 (Optional): Push to Docker Hub${NC}"
echo ""
echo "To enable Docker Hub publishing:"
echo ""
echo "1. Create Docker Hub account at https://hub.docker.com"
echo "2. Create access token:"
echo "   - Account Settings → Security → New Access Token"
echo "3. Add GitHub Secrets:"
echo "   - Go to your repo → Settings → Secrets and variables → Actions"
echo "   - New repository secret:"
echo "     - Name: DOCKERHUB_USERNAME"
echo "     - Value: your-dockerhub-username"
echo "   - New repository secret:"
echo "     - Name: DOCKERHUB_TOKEN"
echo "     - Value: your-access-token"
echo "4. Uncomment the Docker push steps in .github/workflows/cicd.yml"
echo "5. Push changes to trigger pipeline"
echo ""
read -p "Press Enter to continue..."

# Step 9: Test the Pipeline
echo ""
echo -e "${BLUE}Step 9: Test Pipeline Triggers${NC}"
echo ""
echo "Make a small change to test the pipeline:"
echo ""
echo "  # Edit app.py - change version to 1.0.1"
echo "  git add app.py"
echo "  git commit -m 'Update version to 1.0.1'"
echo "  git push"
echo ""
echo "Watch the Actions tab - pipeline should run automatically!"
echo ""

# Final Summary
echo ""
echo "================================"
echo -e "${GREEN}✅ Setup Complete!${NC}"
echo "================================"
echo ""
echo "📁 Project Structure Created:"
echo "   ✓ Flask application (app.py)"
echo "   ✓ Test suite (test_app.py)"
echo "   ✓ Dockerfile"
echo "   ✓ GitHub Actions workflow"
echo "   ✓ Documentation"
echo ""
echo "🎯 What You've Built:"
echo "   ✓ RESTful Flask API"
echo "   ✓ Automated testing with pytest"
echo "   ✓ Docker containerization"
echo "   ✓ CI/CD pipeline with GitHub Actions"
echo "   ✓ Automated deployments"
echo ""
echo "📊 Resume Points:"
echo "   • Developed CI/CD pipeline using GitHub Actions"
echo "   • Implemented Docker containerization"
echo "   • Achieved 95%+ test coverage"
echo "   • Automated testing and deployment"
echo ""
echo "🚀 Next Steps:"
echo "   1. Add more API endpoints"
echo "   2. Integrate a database (PostgreSQL)"
echo "   3. Deploy to cloud (AWS/GCP/Azure)"
echo "   4. Add Kubernetes manifests"
echo "   5. Implement monitoring (Prometheus/Grafana)"
echo ""
echo "📝 Remember to update README.md with your:"
echo "   - GitHub username"
echo "   - Docker Hub username (if using)"
echo "   - LinkedIn profile"
echo ""
echo "Good luck! 🎉"
